<?php
// Simple guard: if page accessed directly without POST data.
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
header('Location: index.html');
exit;
}
function safe($value) {
return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
}
$name = safe($_POST['fullname'] ?? '');
$email = safe($_POST['email'] ?? '');
$phone = safe($_POST['phone'] ?? '');
$course = safe($_POST['course'] ?? '');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Application Summary</title>
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
* {
box-sizing: border-box;
margin: 0;
padding: 0;
}
body {
font-family: "Poppins", sans-serif;
min-height: 100vh;
display: flex;
align-items: center;
justify-content: center;
padding: 20px;
background: radial-gradient(circle at top, #a855f7 0, #1f2937 40%, #020617 100%);
color: #f9fafb;
}
.summary-card {
max-width: 720px;
width: 100%;
background: rgba(15, 23, 42, 0.85);
border-radius: 20px;
padding: 26px 24px 22px;
box-shadow: 0 20px 40px rgba(0, 0, 0, 0.55);
border: 1px solid rgba(148, 163, 184, 0.6);
}
.summary-header {
display: flex;
justify-content: space-between;
align-items: center;
margin-bottom: 18px;
flex-wrap: wrap;
gap: 10px;
}
.summary-header h1 {
font-size: 24px;
}
.status-pill {
padding: 6px 10px;
border-radius: 999px;
font-size: 11px;
display: inline-flex;
align-items: center;
gap: 6px;
background: rgba(22, 163, 74, 0.14);
color: #bbf7d0;
border: 1px solid rgba(34, 197, 94, 0.4);
}
.status-dot {
width: 8px;
height: 8px;
border-radius: 999px;
background: #22c55e;
}
.grid {
display: grid;
grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
gap: 16px 28px;
margin-bottom: 18px;
}
.field-label {
font-size: 11px;
text-transform: uppercase;
letter-spacing: 0.08em;
color: #9ca3af;
margin-bottom: 2px;
}
.field-value {
font-size: 15px;
font-weight: 500;
}
.meta {
display: flex;
justify-content: space-between;
align-items: center;
font-size: 11px;
color: #9ca3af;
margin-top: 6px;
flex-wrap: wrap;
gap: 6px;
}
.btn-row {
display: flex;
justify-content: flex-end;
margin-top: 14px;
gap: 10px;
flex-wrap: wrap;
}
.btn {
border-radius: 999px;
border: none;
cursor: pointer;
font-size: 13px;
padding: 8px 13px;
display: inline-flex;
align-items: center;
gap: 6px;
text-decoration: none;
}
.btn-primary {
background: linear-gradient(135deg, #eab308, #f97316);
color: #111827;
}
.btn-outline {
background: transparent;
color: #e5e7eb;
border: 1px solid rgba(148, 163, 184, 0.8);
}
.btn:hover {
transform: translateY(-1px);
box-shadow: 0 10px 24px rgba(0, 0, 0, 0.35);
}
.btn:active {
transform: translateY(0);
box-shadow: none;
}
@media (max-width: 640px) {
.summary-card {
padding: 20px 18px 18px;
}
}
</style>
</head>
<body>
<div class="summary-card">
<div class="summary-header">
<div>
<h1>Application Submitted </h1>
<p style="font-size: 13px; color: #d1d5db; margin-top: 4px;">
Below is a formatted summary of the information you provided.
</p>
</div>
<div class="status-pill">
<span class="status-dot"></span>
<span>Received &amp; Recorded</span>
</div>
</div>
<div class="grid">
<div>
<div class="field-label">Full Name</div>
<div class="field-value"><?= $name ?></div>
</div>
<div>
<div class="field-label">Email Address</div>
<div class="field-value"><?= $email ?></div>
</div>
<div>
<div class="field-label">Phone Number</div>
<div class="field-value"><?= $phone ?></div>
</div>
<div>
<div class="field-label">Selected Course</div>
<div class="field-value"><?= $course ?></div>
</div>
</div>
<div class="meta">
<span>Thank you for applying. You can go back to edit your details if needed.</span>
<span>Generated by PHP • Simple demo app</span>
</div>
<div class="btn-row">
<a href="index.html" class="btn btn-outline">← Edit Details</a>
<button class="btn btn-primary" onclick="window.print()">
🖨 Print Summary
</button>
</div>
</div>
</body>
</html>
